### ISSUE TITLE
iOS Memory Leak Issue

### ISSUE THREAD

**Issue by NilayDag** [Liftric/KVault#23]
### **New Issue Checklist**
- [x]  I searched for existing GitHub issues

**Info**

I'm using KVault (version 1.2.1) for a Kotlin Multiplatform project.

### **Describe the bug**
kVault iOS main part creates many memory leaks in our project. Most of the leaked objects have a type of CFDictionaryCreateMutable. Here are the places of the leaks:

```
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:188   
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:174
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:176
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:28
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:158
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:176
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:116
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:162
```
...
and so on.  I think the problem occurs because of these **_CF[TYPE]s_**.

Here are my memory leak screenshots in case you need them:

All of the memory leaks are created by **_kVault_**:

<img width="1904" alt="kVault iOS Memory Leak Problems" src="https://user-images.githubusercontent.com/20637243/121525703-57198380-ca01-11eb-9203-e9173d1bc510.png">

Here are the leaked objects:

<img width="1222" alt="kVault iOS Memory Leak Leaked Objects" src="https://user-images.githubusercontent.com/20637243/121525685-52ed6600-ca01-11eb-9cce-85f026ab1d6a.png">

One of the memory leak's stack trace:

<img width="565" alt="kVault One of the Memory Leak Stack Trace" src="https://user-images.githubusercontent.com/20637243/121525711-597bdd80-ca01-11eb-8e4b-a073f118b6b0.png">

Please note that kVault does not create any memory leaks in Android.

**### Expected behavior**
kVault shouldn't create any memory leaks in iOS.

**Comment by benjohnde** [comment]
Thanks for the contribution @NilayDag! Nice find, we've sadly forgotten to release the core foundation references. Fix is subject to release very soon! Glad you are using or at least trying out KVault :) 👍 🚀 🎉

**Comment by gaebel** [comment]
We've just published a new version containing the memory leak fix. It will probably take around 1 to 2 hours until the release gets synced to MavenCentral. You can add the following repository to access the release now:

```kotlin
repositories {
    maven(url = "https://s01.oss.sonatype.org/content/repositories/releases")
}
```
