### ISSUE TITLE
iOS Memory Leak 2

### ISSUE THREAD

**Issue by NilayDag** [Liftric/KVault#25]
### **New Issue Checklist**
- [x] I updated kVault to version: 1.4.1

### **Describe the bug**
Thank you for your previous fix about the issue. Although new updated version seems to fix the significant number of leaks, there are still remaining leaks. Here are the places of the leaks:

```
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:46
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:196
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:240
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:254
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:256
>  KVault/kvault/src/iosMain/kotlin/com/liftric/kvault/KVault.kt:268
```
May be using **_weak_** references could resolve this problem.

Here are my memory leak screenshots in case you need them:

Memory leaks that created by **_kVault_**:

<img width="1904" alt="Memory Leaks Created by KVault" src="https://user-images.githubusercontent.com/20637243/121639541-59c5b880-ca95-11eb-85ab-ccc6c0a7589c.png">

Some of the memory leak's stack trace:

<img width="556" alt="Leak Stack Trace 1" src="https://user-images.githubusercontent.com/20637243/121640762-005e8900-ca97-11eb-8b39-6084a2a3e8ef.png">

<img width="558" alt="Leak Stack Trace 2" src="https://user-images.githubusercontent.com/20637243/121639793-bfb24000-ca95-11eb-8911-7983d312dc3b.png">

**### Expected behavior**
kVault shouldn't create any memory leaks in iOS.

**Comment by benjohnde** [comment]
Thanks again for your contribution @NilayDag! We will hopefully have a fix for the outstanding memory leaks very soon! :)

**Comment by gaebel** [comment]
The memory leaks are fixed in the latest release :)
