### ISSUE TITLE
Add library to multiplatform library lists

### ISSUE THREAD

**Issue by ln-12** [Liftric/KVault#27]
Hey, your library is exactly what I was looking for! Unfortunately, it was a bit hard for me to find out. What do you think about adding it to some KMM library lists?

For example:
https://github.com/AAkira/Kotlin-Multiplatform-Libraries
https://github.com/icerockdev/libs.kmp.icerock.dev

That would make it much easier to find it :)

**Comment by benjohnde** [comment]
Oh, hey there @ln-12 👋 ! Lovely to hear that! Thanks that's actually a solid hint for us! I am going to look further into that tomorrow morning.

**Comment by gaebel** [comment]
I've created a PR in both repos.
