### ISSUE TITLE
SharedPreferences `fileName` argument injection

### ISSUE THREAD

**Issue by AfanasievAnton** [Liftric/KVault#29]
Hi looking on Android implementation of KVault it looks like its API does not allow custom sharedPreferences name.

```
 encSharedPrefs = EncryptedSharedPreferences.create(
            context,
            "secure-shared-preferences", 
            masterKey,
            EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
        )
```
        
The "secure-shared-preferences" is hardcoded. Is it possible to add a second argument to KVault constructor with default value, so that at least there will be an option to give a unique fileName.

**Comment by gaebel** [comment]
Hi @AfanasievAnton, yes we can do this. Could you create a PR with this change?

**Comment by AfanasievAnton** [comment]
Thanks @gaebel , unfortunately I keep getting permission denied when trying to upload a side branch with this chages.

**Comment by gaebel** [comment]
You can't push directly into the repository. You have to [create a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and then a [PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) with the changes in the forked repo.

**Comment by gaebel** [comment]
I've implemented the feature in the latest release.
