### ISSUE TITLE
Add support for retrieving all keys

### ISSUE THREAD

**Issue by mandrachek** [Liftric/KVault#32]
Needs a way to retrieve all currently stored keys.

**Comment by gaebel** [comment]
What's your use-case for this feature?

**Comment by mandrachek** [comment]
1: Say I have 20 values stored, and I want to remove all but the three. This is easy to accomplish if I don't have to keep my own list of all keys used, and instead can get the list of all keys, filter out the ones I want to keep, then remove the remaining entries.

2: It can be useful in a debugging context, being able to log the list of keys stored.

**Comment by gaebel** [comment]
Check, I'll publish a new release with this feature tomorrow or on Wednesday.
