### ISSUE TITLE
API as an interface

### ISSUE THREAD

**Issue by cleemansen** [Liftric/KVault#42]
Hello, it would be create if the lib exposes its API as an interface.

With that adjustment classes that depends on your API are testable b/c popular multiplatform mocking libraries are only support to mock interfaces [[MockKMP](https://github.com/kosi-libs/MocKMP)] [[Mockative](https://github.com/mockative/mockative)].

Best

**Comment by benjohnde** [comment]
That's a good idea! Feel free to give it a try with a contribution 🎉
